// Estilos compartidos del panel de configuración de nodos (tema oscuro del editor).
export const S = {
  label: {
    fontSize: 10,
    color: '#64748b',
    fontWeight: 700,
    letterSpacing: '0.06em',
    marginBottom: 4,
    display: 'block',
  },
  hint: {
    fontSize: 10,
    color: '#475569',
    marginTop: 3,
  },
  input: {
    width: '100%',
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 6,
    color: '#e2e8f0',
    fontSize: 12,
    padding: '6px 9px',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    outline: 'none',
  },
  textarea: {
    width: '100%',
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 6,
    color: '#e2e8f0',
    fontSize: 12,
    padding: '6px 9px',
    resize: 'vertical',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    outline: 'none',
    minHeight: 80,
  },
  select: {
    width: '100%',
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: 6,
    color: '#e2e8f0',
    fontSize: 12,
    padding: '6px 9px',
    boxSizing: 'border-box',
    fontFamily: 'inherit',
    outline: 'none',
    cursor: 'pointer',
  },
  checkRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  fieldWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
}
